export const SITE = {
  name: "MhorKub",
  nameTh: "หมอคับ",
  tagline: "ระบบบริหารคลินิกอัจฉริยะ",
  taglineEn: "Intelligent Clinic Management System",
  description: "ระบบบริหารคลินิกครบวงจร จัดการคนไข้ คิว ใบสั่งยา สต็อก บิล พร้อม AI ช่วยวินิจฉัย — ใช้งานได้ทั้งออนไลน์และออฟไลน์",
  url: "https://mhorkub.com",
} as const;

export const NAV_LINKS = [
  { href: "/", label: "หน้าหลัก" },
  { href: "/features", label: "ฟีเจอร์" },
  { href: "/pricing", label: "ราคา" },
  { href: "/blog", label: "บทความ" },
  { href: "/about", label: "เกี่ยวกับเรา" },
  { href: "/contact", label: "ติดต่อ" },
] as const;

export const FEATURES = [
  {
    icon: "Users",
    title: "จัดการคนไข้",
    titleEn: "Patient Management",
    description: "บันทึกข้อมูลคนไข้ครบถ้วน ประวัติการรักษา แพ้ยา โรคประจำตัว ค้นหาได้ทันที",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop",
  },
  {
    icon: "ClipboardList",
    title: "ระบบคิวอัจฉริยะ",
    titleEn: "Smart Queue",
    description: "จัดคิวอัตโนมัติ แสดงผลบนจอ คนไข้ดูคิวผ่านมือถือได้ ไม่ต้องรอนาน",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop",
  },
  {
    icon: "Stethoscope",
    title: "บันทึกการตรวจ",
    titleEn: "Medical Records",
    description: "SOAP Notes, Body Map, ICD Code พร้อม AI ช่วยแปลงเสียงเป็นบันทึก",
    image: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?w=600&h=400&fit=crop",
  },
  {
    icon: "Pill",
    title: "ใบสั่งยา & สต็อก",
    titleEn: "Prescription & Inventory",
    description: "สั่งยา เช็คแพ้ยา ตัดสต็อกอัตโนมัติ แจ้งเตือนยาใกล้หมด",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=400&fit=crop",
  },
  {
    icon: "Receipt",
    title: "บิล & การเงิน",
    titleEn: "Billing & Finance",
    description: "ออกบิล รับชำระ พิมพ์ใบเสร็จ สรุปรายได้ ครบจบในที่เดียว",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop",
  },
  {
    icon: "Brain",
    title: "AI ช่วยวินิจฉัย",
    titleEn: "AI-Assisted Diagnosis",
    description: "แปลงเสียงเป็น SOAP อัตโนมัติ แนะนำการวินิจฉัย สั่งยา ด้วย AI",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop",
  },
] as const;

export const PRICING_TIERS = [
  {
    name: "ทดลองใช้",
    nameEn: "Trial",
    price: "ฟรี",
    priceNum: 0,
    period: "14 วัน",
    periodDays: 14,
    features: [
      "ฟีเจอร์ครบทุกอย่าง",
      "คนไข้ไม่จำกัด",
      "AI 20 ครั้ง",
      "เครื่องเดียว",
    ],
    cta: "เริ่มทดลองฟรี",
    highlighted: false,
  },
  {
    name: "รายเดือน",
    nameEn: "Monthly",
    price: "1,200",
    priceNum: 1200,
    period: "บาท / เดือน",
    periodDays: 30,
    features: [
      "คนไข้ไม่จำกัด",
      "AI ไม่จำกัด",
      "3 เครื่อง",
      "สำรองข้อมูลอัตโนมัติ",
      "ซัพพอร์ตทาง LINE",
    ],
    cta: "สมัครเลย",
    highlighted: false,
  },
  {
    name: "6 เดือน",
    nameEn: "Semi-Annual",
    price: "6,000",
    priceNum: 6000,
    period: "บาท / 6 เดือน",
    periodDays: 180,
    features: [
      "คนไข้ไม่จำกัด",
      "AI ไม่จำกัด",
      "5 เครื่อง",
      "สำรองข้อมูลอัตโนมัติ",
      "ซัพพอร์ตทาง LINE",
      "ประหยัด 17%",
    ],
    cta: "สมัครเลย",
    highlighted: true,
  },
  {
    name: "รายปี",
    nameEn: "Yearly",
    price: "10,000",
    priceNum: 10000,
    period: "บาท / ปี",
    periodDays: 365,
    features: [
      "คนไข้ไม่จำกัด",
      "AI ไม่จำกัด",
      "เครื่องไม่จำกัด",
      "สำรองข้อมูลอัตโนมัติ",
      "ซัพพอร์ตเฉพาะทาง",
      "ประหยัด 31%",
    ],
    cta: "สมัครเลย",
    highlighted: false,
  },
] as const;
